### ISSUE TITLE
how can i use this library on edison ?

### ISSUE THREAD

**Issue by windmillknight** [jonnypage-d3/hooloovoo#3]
when I use this library on intel edison board ,it catch a error said :
/home/root/node_modules/iot-sol/node_modules/hooloovoo/node_modules/rpio/lib/rpio.js:144
                throw "Unable to determine board revision";
                ^
Unable to determine board revision

**Comment by jonnypage-d3** [comment]
Have you tried using the [rpio ](https://github.com/jperkin/node-rpio) library by it's self on your edison? hooloovoo uses rpio as a dependency. It looks like it's being thrown there. I'm not sure it's compatible with non-pi devices.
